clean: true
author: WeTransfer
author_url: https://wetransfer.com
documentation: docs/*.md
github_url: https://github.com/WeTransfer/UINotifications
github_file_prefix: https://github.com/WeTransfer/UINotifications/tree/master
umbrella_header: UINotifications/UINotifications.h
framework_root: UINotifications
module: UINotifications
skip_undocumented: true
hide_documentation_coverage: true
theme: fullwidth
sdk: iphonesimulator
readme: README.md
